
logging:
  level:
    root: INFO
#    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
#    org.springframework.cloud.gateway: TRACE
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE
#    org.springframework.security.web: DEBUG
#    org.springframework.http.server.reactive: TRACE
#    org.springframework.web.reactive: TRACE
#    org.springframework.boot.autoconfigure.web: DEBUG
#    reactor.netty: DEBUG

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

server:
  port: 8090

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

base-url: "http://localhost:8090"

logout-success-url: "/main/MainPage"

spring:
  application:
    name: gateway
  profiles:
    include: management

# http://localhost:9080/realms/careeasy/well-known/openid-configuration
#  security.oauth2.resourceserver.jwt.jwk-set-uri: http://${app.auth-server}:9000/.well-known/jwks.json
  security:
    oauth2:
      client:
        registration:
          adminapp:
            provider: keycloak
            client-id: adminapp
            # change CLIENT_SECRET below with the secret generated by Keycloak for the mywebapp client
            client-secret: adminapp
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/example"
            scope: openid
        provider:
          keycloak:
            issuer-uri: "https://auth.xr-friends.com/ev/realms/example"

  cloud:
    gateway:
      default-filters:
        - TokenRelay
#        - CircuitBreaker=myCircuitBreaker
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#          predicates:
#            - name: Path
#              args:
#                pattern: "'/services/'+serviceId.toLowerCase()+'/**'"
#          filters:
#            - name: RewritePath
#              args:
#                regexp: "'/services/'+serviceId.toLowerCase()+'/(?<remaining>.*)'"
#                replacement: "'/${remaining}'"
      httpclient:
        pool:
          max-connections: 1000
      routes:
        - id: bff
          uri: http://localhost:8091
          predicates:
            - Path=/services/bff/**
        - id: abc
          uri: http://localhost:8082
          predicates:
            - Path=/services/abc/**
        - id: xyz
          uri: http://localhost:8083
          predicates:
            - Path=/services/xyz/**
        - id: orders
          uri: http://localhost:8084
          predicates:
            - Path=/services/orders/**
        - id: bfi
          uri: http://localhost:8085
          predicates:
            - Path=/services/bfi/**

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          [
            'configprops',
            'env',
            'health',
            'info',
            'logfile',
            'loggers',
            'prometheus',
            'threaddump',
          ]
  endpoint:
    health:
      show-details: when_authorized
      roles: 'ROLE_ADMIN'
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
  info:
    git:
      mode: full
    env:
      enabled: true
  health:
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true
  metrics:
    export:
      # Prometheus is the default metrics backend
      prometheus:
        enabled: true
        step: 60
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
    tags:
      application: ${spring.application.name}
    web:
      server:
        request:
          autotime:
            enabled: true
